[[pages]]
name = "Section"
is_section = true
icon = ""

[[pages]]
path = "login.py"
name = "Login"
icon = ""

[[pages]]
path = "productPage.py"
name = "Webshop"
icon = ""

[[pages]]
path = "cart.py"
name = "Cart"
icon = ""

[[pages]]
path = "orders.py"
name = "Orders"
icon = ""