[[pages]]
name = "Section"
is_section = true
icon = ""

[[pages]]
path = "login.py"
name = "Login"
icon = ""

[[pages]]
path = "productPage.py"
name = "Product Catalog"
icon = ""

[[pages]]
path = "singleProductPage.py"
name = "Product"
icon = ""